name: Gitops pipeline with Argocd

on:
  push:
      branches:
            - main
      paths-ignore:
            - 'manifest/**'  # Prevent infinite loop when updating manifests
env:
  PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
  ARGOCD_USERNAME: ${{ secrets.ARGOCD_USERNAME }}
  ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
  GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
  GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
  
jobs:
    build:
        runs-on: ubuntu-latest  # Changed from self-hosted runner to GitHub-hosted
        timeout-minutes: 30     # Add timeout to prevent hanging
        steps:
            - name: checkout code
              uses: actions/checkout@v3
              with:
               token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
               fetch-depth: 0
               
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '14'
                  
            - name: Install Node.js dependencies
              run: npm install
              
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
              
            - name: Build Docker image
              run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ github.sha}} .

            - name: Scan Docker Image with Trivy
              run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ github.sha }}

            - name: Log in to DockerHub
              run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
              
            - name: Push Docker image to DockerHub
              run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ github.sha }}

    deploy:
        needs: build
        runs-on: ubuntu-latest
        timeout-minutes: 15     # Add timeout to prevent hanging
        steps: 
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
                fetch-depth: 0  # get all history of all branches and tags

            - name: Install kubectl
              run: |
                  curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.30.7/2024-12-12/bin/linux/amd64/kubectl
                  chmod +x ./kubectl
                  sudo mv ./kubectl /usr/local/bin/kubectl

            - name: Install ArgoCD CLI
              run: | 
                  curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
                  chmod +x argocd
                  sudo mv argocd /usr/local/bin/argocd
                  
            - name: Login to ArgoCD
              run: |
                echo "Logging into ArgoCD server: ${{ secrets.ARGOCD_SERVER }}"
                argocd login ${{ secrets.ARGOCD_SERVER }} \
                    --username ${{ secrets.ARGOCD_USERNAME }} \
                    --password ${{ secrets.ARGOCD_PASSWORD }} \
                    --insecure
                    
            - name: Update deployment.yaml with newly built image
              run: |
                git config user.name "${{ secrets.GIT_USERNAME }}"
                git config user.email "${{ secrets.GIT_EMAIL }}"
                git fetch origin
                git checkout main
                git pull origin main
                echo "Current working directory: $(pwd)"
                echo "Before update:"
                cat manifest/deployment.yaml
                sed -i "s+${{ secrets.DOCKERHUB_USERNAME }}/my-app.*+${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ github.sha }}+g" manifest/deployment.yaml
                echo "After update:"
                cat manifest/deployment.yaml

            - name: Commit and Push Updated deployment.yaml
              run: |
                git config user.name "${{ secrets.GIT_USERNAME }}"
                git config user.email "${{ secrets.GIT_EMAIL }}"
                git remote set-url origin https://${{ secrets.GIT_USERNAME }}:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git
                git fetch origin
                git checkout main
                git pull origin main
                git add .
                # Only commit if there are changes
                if git diff --staged --quiet; then
                  echo "No changes to commit"
                else
                  git commit -m "Update image to my-app:${{ github.sha }} [skip ci]"
                  git push origin main
                fi

            - name: Refresh ArgoCD App and Sync
              run: |
                echo "Syncing ArgoCD application: my-app"
                argocd app sync my-app
                echo "Checking application status:"
                argocd app get my-app

            
      
